---
- name: Create directory
  file:
    path: ~/web
    state: directory

- name: Copy zipped artifact
  template:
    src: "tar -xvzf artifact.tar.gz"
    dest: "~/web/index.js"

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Stop server"
  become: yes
  command: pm2 stop default

- name: "Start server"
  become: yes
  command: pm2 start npm -- start
